from typing import Optional


class Orchestrator:
    def __init__(self, policy_yaml: str) -> None: ...
    def process(
        self,
        thread_id: str,
        step: int,
        tool_name: str,
        arguments: str,
    ) -> Optional[Intervention]: ...
    def get_metrics(self) -> RecoveryMetrics: ...


class Intervention:
    def is_continue(self) -> bool: ...
    def is_abort(self) -> bool: ...
    def is_retry(self) -> bool: ...
    def is_replace_tool(self) -> bool: ...
    def is_inject_prompt(self) -> bool: ...
    def reason(self) -> Optional[str]: ...
    def delay_ms(self) -> Optional[int]: ...
    def prompt_content(self) -> Optional[str]: ...


class RecoveryMetrics:
    def intervention_count(self) -> int: ...
    def prevented_calls(self) -> int: ...
    def recovery_time_ms(self) -> int: ...
    def to_json(self) -> str: ...
